=begin
#MicroCMS API

#MicroCMSのコンテンツを取得するAPIです。リスト形式のAPIではコンテンツ一覧、オブジェクト形式のAPIでは単一コンテンツを取得できます。

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MicroCMS::ManagementApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ManagementApi' do
  before do
    # run before each test
    @api_instance = MicroCMS::ManagementApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ManagementApi' do
    it 'should create an instance of ManagementApi' do
      expect(@api_instance).to be_instance_of(MicroCMS::ManagementApi)
    end
  end

  # unit tests for api_v1_contents_endpoint_content_id_created_by_patch
  # コンテンツの作成者の変更
  # PATCH APIを使用して、指定したコンテンツの作成者を変更します。 
  # @param endpoint 対象のエンドポイント
  # @param content_id 更新対象のコンテンツID
  # @param api_v1_contents_endpoint_content_id_created_by_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [ApiV1ContentsEndpointContentIdCreatedByPatch200Response]
  describe 'api_v1_contents_endpoint_content_id_created_by_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_contents_endpoint_content_id_patch
  # コンテンツの公開状態の変更
  # PATCH APIを使用して、コンテンツの公開状態（公開中または下書き中）を変更します。 
  # @param endpoint 対象のエンドポイント
  # @param content_id 更新対象のコンテンツID
  # @param api_v1_contents_endpoint_content_id_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [ApiV1ContentsEndpointContentIdPatch200Response]
  describe 'api_v1_contents_endpoint_content_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_contents_endpoint_get
  # コンテンツ一覧の取得
  # リスト形式のAPIにおいてはコンテンツのメタ情報一覧が取得でき、オブジェクト形式のAPIにおいては単一コンテンツのメタ情報が取得ができます。 
  # @param endpoint 対象のエンドポイント
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得件数の指定
  # @option opts [Integer] :offset コンテンツの取得開始位置を指定します。
  # @return [ApiV1ContentsEndpointGet200Response]
  describe 'api_v1_contents_endpoint_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_media_delete
  # メディアの削除
  # MicroCMSサービスに含まれる指定URLのメディアを削除します。 
  # @param url 削除対象のメディアのURLを指定します（カスタムドメインでも指定可能）。
  # @param [Hash] opts the optional parameters
  # @return [ApiV2MediaDelete200Response]
  describe 'api_v2_media_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v2_media_get
  # メディア情報の取得
  # MicroCMSサービスに含まれるメディア情報を取得します。 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するメディア情報の件数（デフォルトは10、上限は100）。
  # @option opts [Boolean] :image_only trueの場合、画像のみを取得します（デフォルトはfalse）。 
  # @option opts [String] :file_name 部分一致するファイル名でメディアを絞り込みます。
  # @option opts [String] :token 前回のリクエストで取得したtokenを指定すると続きから取得できます。
  # @return [ApiV2MediaGet200Response]
  describe 'api_v2_media_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
