=begin
#MicroCMS API

#MicroCMSのコンテンツを取得するAPIです。リスト形式のAPIではコンテンツ一覧、オブジェクト形式のAPIでは単一コンテンツを取得できます。

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MicroCMS::ApiV1ContentsEndpointContentIdCreatedByPatchRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MicroCMS::ApiV1ContentsEndpointContentIdCreatedByPatchRequest do
  let(:instance) { MicroCMS::ApiV1ContentsEndpointContentIdCreatedByPatchRequest.new }

  describe 'test an instance of ApiV1ContentsEndpointContentIdCreatedByPatchRequest' do
    it 'should create an instance of ApiV1ContentsEndpointContentIdCreatedByPatchRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(MicroCMS::ApiV1ContentsEndpointContentIdCreatedByPatchRequest)
    end
  end

  describe 'test attribute "created_by"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
