=begin
#MicroCMS API

#MicroCMSのコンテンツを取得するAPIです。リスト形式のAPIではコンテンツ一覧、オブジェクト形式のAPIでは単一コンテンツを取得できます。

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MicroCMS::ContentMetadataReservationTime
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MicroCMS::ContentMetadataReservationTime do
  let(:instance) { MicroCMS::ContentMetadataReservationTime.new }

  describe 'test an instance of ContentMetadataReservationTime' do
    it 'should create an instance of ContentMetadataReservationTime' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(MicroCMS::ContentMetadataReservationTime)
    end
  end

  describe 'test attribute "publish_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "stop_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
